apiVersion: apps/v1
kind: Deployment
metadata:
  name: palindrome-api
spec:
  selector:
    matchLabels:
      app: palindrome-api
  template:
    metadata:
      labels:
        app: palindrome-api
    spec:
      containers:
        - name: palindrome-api
          image: palindrome-api:latest
          imagePullPolicy: Never
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: MYSQL_HOST
              value: "db"
            - name: MYSQL_DATABASE
              value: "palindrome"
            - name: MYSQL_USER
              value: "username"
            - name: MYSQL_PASSWORD
              value: "secretpassword"
            - name: SPRING_PROFILES_ACTIVE
              value: "scalable"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: palindrome-api
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: palindrome-api
  targetCPUUtilizationPercentage: 75
---
apiVersion: v1
kind: Service
metadata:
  name: palindrome-api
spec:
  selector:
    app: palindrome-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mysql:8.0
          env:
            - name: MYSQL_DATABASE
              value: "palindrome"
            - name: MYSQL_USER
              value: "username"
            - name: MYSQL_PASSWORD
              value: "secretpassword"
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "true"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - name: db
      port: 3306
      targetPort: 3306
